# The sequence of triangle numbers is generated by adding the natural numbers.
# The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

# Listing the factors of the first six triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21

# What is the first triangle number to have over five hundred divisors?

def factor_count(x)
  range = 2..Math.sqrt(x)
  count = range.count { |i| x % i == 0 }
  count * 2
end

tri_numbers = Enumerator.new do |out|
  num = 0
  inc = 1
  while num += inc
    out << num
    inc += 1
  end
end

puts tri_numbers.find { |x| 500 < factor_count(x) }
# 76_576_500
