// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// Sum the even terms in the Fibonacci sequence under four million

fn main() {
    let mut sum = 0;
    let mut a = 2;
    let mut b = 3;
    let mut c = 5;
    while a < 4_000_000 {
        sum += a;
        a = b + c;
        b = c + a;
        c = a + b;
    }
    println!("{}", sum)
}
// 4613732
