; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
; By starting with 1 and 2, the first 10 terms will be:
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; Sum the even terms in the Fibonacci sequence under four million

(def fibs
  (lazy-cat [0 1]
    (map + fibs (rest fibs))))

(defn fibs-under [limit]
  (reduce +
    (take-while #(< % limit)
      (take-nth 3 fibs))))
      ; every 3rd fib is even

(println
  (fibs-under 4000000))
; 4613732
