// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//Sum the even terms in the Fibonacci sequence under four million

class MainClass
{
  static void Main()
  {
    int sum = 0;
    int a = 1;
    int b = 1;
    int c = a + b;
    while (c <= 4000000)
    {
      sum += c;
      a = b + c;
      b = c + a;
      c = a + b;
    }
    System.Console.WriteLine(sum);
  }
}
// 4613732
