-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- Sum the even terms in the Fibonacci sequence under four million

nextFib x = [sum x, (last x) + (sum x)]

fibs = concat (iterate nextFib [0, 1])

total = sum (filter even (takeWhile (\x -> x < 4000000) fibs))

main = putStrLn (show total)
-- 4613732
