// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// Sum the even terms in the Fibonacci sequence under four million

const std = @import("std");
const stdout = std.io.getStdOut().writer();

pub fn main() !void {
    var total: u32 = 0;
    var a: u32 = 1;
    var b: u32 = 2;
    var c: u32 = 0;

    while (b < 4000000) {
        total += b;
        c = a + b;
        a = b + c;
        b = a + c;
    }

    try stdout.print("{d}\n", .{total});
}
// 4613732
