;;  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;;  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;;  total the even fibs under 4m


(def fibs
    (lazy-cat [0 1]
              (map + fibs (rest fibs))))


(def fibs (range 0 4000000 3))


