// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// Sum the even terms in the Fibonacci sequence under four million

public class p2 {
  public static Integer sum_even_fibs_under(int limit) {
    long start = System.nanoTime();
    int total = 0;
    int a = 1;
    int b = 2;
    int next;
    while(b < limit) {
      total += b;
      next = a + b;
      a = b;
      b = next;
      next = a + b;
      a = b;
      b = next;
      next = a + b;
      a = b;
      b = next;
    }
    System.out.println(System.nanoTime() - start);
    return total;
  }

  public static void main(String[] args) {
    System.out.println(sum_even_fibs_under(4000000));
  }
}

// 4613732
