# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

start = [0, 1]
total = 0
until start.last >= 4_000_000
    start << start[-1] + start[-2]
    if start.last % 2 == 0
        total += start.last
    end
    start.shift
end


p total

# 4613732
